import { useTranslation } from "next-i18next";
import Head from "next/head";
import { useRouter } from "next/router";

const Helmet: React.FC<{ title?: string; children: React.ReactNode }> = ({
  title,
  children,
}): React.ReactElement => {
  const { pathname } = useRouter();
  const { t } = useTranslation();

  const tit = pathname === "/" ? t("home") : t(pathname?.split("/")[1] as any);
  const res = tit ? t("domain") + " | " + tit : t("domain");

  return (
    <>
      <Head>
        <title>{res}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </>
  );
};

export default Helmet;
