import { useTranslation } from "next-i18next";
import Head from "next/head";
import { useRouter } from "next/router";
import dictionary from "../../public/locales/fa/common.json";

export const dic = (() =>
  ({
    ...Object.keys(dictionary)
      .filter((k) => isNaN(Number(k)))
      .reduce(
        (acc, cur) => ({
          ...acc,
          [cur]: cur,
        }),
        {}
      ),
  } as {
    [k in keyof typeof dictionary]: k;
  }))();

export type TranslationKeys = keyof typeof dic;

const Helmet: React.FC<{ title?: string; children: React.ReactNode }> = ({
  title,
  children,
}): React.ReactElement => {
  const { pathname } = useRouter();
  const { t } = useTranslation();

  const tit =
    pathname === "/"
      ? t("home")
      : t(pathname?.split("/")[1] as TranslationKeys);
  const res = tit ? t("domain") + " | " + tit : t("domain");

  return (
    <>
      <Head>
        <title>{res}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </>
  );
};

export default Helmet;
